### ISSUE TITLE
Make ambiguous transitivity tag (+IT?)

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/udar#24]
Russian verbs do not inflect for transitivity, so having multiple readings distinguished by transitivity is grammatically inaccurate.

Transitivity tags can be helpful for the CG, so we should specify transitivity when possible, but if the transitivity is ambiguous, there should only be one reading.

**Comment by reynoldsnlp** [comment]
@snomos Do you know if any GT languages have an ambiguous transitivity tag? If not, do you see anything wrong with using `+IT`?

**Comment by reynoldsnlp** [comment]
The idea is to change...

```
$ echo читает | hurus
читает	читать+V+Impf+IV+Prs+Sg3	5.498047
читает	читать+V+Impf+TV+Prs+Sg3	5.498047
```

...into...

```
$ echo читает | hurus
читает	читать+V+Impf+IT+Prs+Sg3	5.498047
```

**Comment by snomos** [comment]
I see no major problem, the only detail is that I would probably let the tag be +ITV to make it resemble the other two tags more. An alternative tag format that has been introduced in Greenlandic is +Gram/ITV, where the +Gram/ tag prefix (or domain, so to speak) indicates grammatical information that is not expressed through morphology. Transitivity is an obvious property to specify this way, but one can imagine other grammatical features as well.

If you want to discuss this with a larger audience, I suggest you join our Zulip community: https://giella.zulipchat.com (available both through a stand-alone client, and via a web page). I'll send you an invitation that you can discard if you are not interested :)

**Comment by reynoldsnlp** [comment]
Moved to https://github.com/giellalt/lang-rus/issues/4
