### ISSUE TITLE
Which hfst-dev package has to be used?

### ISSUE THREAD

**Issue by Vuizur** [reynoldsnlp/udar#52]
Hi,

I am really interested in trying this program and am currently trying to install it.

I tried following the instructions for Debian/Ubuntu, but I got the error that "hfst-dev" package doesn't exist in the package repository. Is the required library maybe [libhfst-dev](https://packages.ubuntu.com/bionic/libhfst-dev)?

It would also maybe be nice if the required Python version would be specified in the Readme, because if I understood it correctly hfst doesn't work with newer Pythons.

Have a great day!

**Comment by reynoldsnlp** [comment]
@Vuizur I just updated the instructions on the readme to reflect changes in the HFST packaging, so if you are using Ubuntu you can `apt-get install cg3 hfst python3-hfst` and it should work. If it works for you, feel free to close this issue.

**Comment by Vuizur** [comment]
Thank you very much for the help! It runs now. (Sorry for the late answer.)

I installed it on WSL with Ubuntu 20.04 and Python 3.6 using pyenv (and installed everything using poetry). To get it to run I had to install a weird stanza beta version from TestPypi though because the current version crashed on my end. (Like detailed [here](https://github.com/stanfordnlp/stanza/issues/1126)).
